name: Random Trivia Update

on:
  push:
    branches: [master]
#   schedule:
#     - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "some text\n" > $GITHUB_WORKSPACE/README.md
        echo "#test, and deploy your project" >> $GITHUB_WORKSPACE/README.md
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes  
        
