name: Random Trivia Update

on:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "## :smile: Hello! Did you know that... :smile:" > $GITHUB_WORKSPACE/README.md
        curl http://numbersapi.com/random/trivia >> $GITHUB_WORKSPACE/README.md
        (echo && echo && echo "<sup>(come back in 5 minutes for the next trivia)</sup>") >> $GITHUB_WORKSPACE/README.md
        (echo && echo && echo "<sup>Credits: http://numbersapi.com</sup>") >> $GITHUB_WORKSPACE/README.md
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        commit_user_name: GitHub Actions Bot
        commit_user_email: github-actions-bot@github.com
        commit_author: GitHub Actions Bot <github-actions-bot@github.com>  
